apiVersion: v1
kind: Secret
metadata:
  name: trino-query-log-sink
  namespace: trino
  labels:
    app.kubernetes.io/name: trino-query-log-sink
type: Opaque
stringData:
  TRINO_PASSWORD: ""
  TRINO_ACCESS_TOKEN: ""
  TRINO_SSL: "false"
