-- Trino Query Log Sink — ClickHouse DDL
--
-- Database/table here match the service defaults (CLICKHOUSE_DATABASE /
-- CLICKHOUSE_TABLE); change both together if you override them. Retention is
-- applied by the prune subcommand (partition drops), so no TTL is defined; add
-- one yourself if you prefer server-side expiry.
--
-- This file is generated by `STORE_BACKEND=clickhouse trino-query-log-sink ddl`;
-- the running service can apply the same statements with
-- `STORE_BACKEND=clickhouse trino-query-log-sink init`.

CREATE DATABASE IF NOT EXISTS "observability";

CREATE TABLE IF NOT EXISTS "observability"."trino_query_log" (
  "query_id" String,
  "query_state" LowCardinality(String),
  "query_type" LowCardinality(String),
  "user_name" LowCardinality(String),
  "source" String,
  "principal" String,
  "client_tags" String,
  "catalog" LowCardinality(String),
  "schema_name" LowCardinality(String),
  "query_text" String CODEC(ZSTD(3)),
  "query_preview" String,
  "update_type" LowCardinality(String),
  "create_time" DateTime64(6, 'UTC'),
  "execution_start_time" Nullable(DateTime64(6, 'UTC')),
  "end_time" Nullable(DateTime64(6, 'UTC')),
  "queued_ms" Int64,
  "analysis_ms" Int64,
  "planning_ms" Int64,
  "execution_ms" Int64,
  "wall_ms" Int64,
  "cpu_ms" Int64,
  "peak_user_memory_bytes" Int64,
  "peak_total_memory_bytes" Int64,
  "physical_input_bytes" Int64,
  "physical_input_rows" Int64,
  "processed_input_bytes" Int64,
  "processed_input_rows" Int64,
  "output_bytes" Int64,
  "output_rows" Int64,
  "written_bytes" Int64,
  "written_rows" Int64,
  "completed_splits" Int64,
  "error_code" LowCardinality(String),
  "error_type" LowCardinality(String),
  "error_message" String CODEC(ZSTD(3)),
  "plan" String CODEC(ZSTD(6)),
  "json_plan" String CODEC(ZSTD(6)),
  "inputs_json" String CODEC(ZSTD(3)),
  "resource_group" LowCardinality(String),
  "server_version" LowCardinality(String),
  "environment" LowCardinality(String),
  "ingested_at" DateTime64(6, 'UTC') DEFAULT now64(6),
  INDEX qid_bf "query_id" TYPE bloom_filter(0.01) GRANULARITY 1
)
ENGINE = ReplacingMergeTree("ingested_at")
PARTITION BY toDate("create_time")
ORDER BY ("create_time", "query_id")
SETTINGS non_replicated_deduplication_window = 1000;
