-- Trino Query Log Sink — Iceberg DDL
--
-- Catalog/schema/table here match the service defaults (TRINO_CATALOG /
-- TRINO_SCHEMA / TRINO_TABLE); change all three together if you override them.
-- Replace the location bucket below with your Iceberg warehouse, or drop the
-- WITH (location=...) clause if the catalog already has a warehouse configured.
--
-- This file is generated by `trino-query-log-sink ddl`; the running service can
-- apply the same statements with `trino-query-log-sink init`.

CREATE SCHEMA IF NOT EXISTS "gravitino"."observability" WITH (location = 'gs://CHANGE_ME-warehouse/observability');

CREATE TABLE IF NOT EXISTS "gravitino"."observability"."trino_query_log" (
  "query_id" varchar,
  "query_state" varchar,
  "query_type" varchar,
  "user_name" varchar,
  "source" varchar,
  "principal" varchar,
  "client_tags" varchar,
  "catalog" varchar,
  "schema_name" varchar,
  "query_text" varchar,
  "query_preview" varchar,
  "update_type" varchar,
  "create_time" timestamp(6) with time zone,
  "execution_start_time" timestamp(6) with time zone,
  "end_time" timestamp(6) with time zone,
  "queued_ms" bigint,
  "analysis_ms" bigint,
  "planning_ms" bigint,
  "execution_ms" bigint,
  "wall_ms" bigint,
  "cpu_ms" bigint,
  "peak_user_memory_bytes" bigint,
  "peak_total_memory_bytes" bigint,
  "physical_input_bytes" bigint,
  "physical_input_rows" bigint,
  "processed_input_bytes" bigint,
  "processed_input_rows" bigint,
  "output_bytes" bigint,
  "output_rows" bigint,
  "written_bytes" bigint,
  "written_rows" bigint,
  "completed_splits" bigint,
  "error_code" varchar,
  "error_type" varchar,
  "error_message" varchar,
  "plan" varchar,
  "json_plan" varchar,
  "inputs_json" varchar,
  "resource_group" varchar,
  "server_version" varchar,
  "environment" varchar
) WITH (
  partitioning = ARRAY['day(create_time)'],
  sorted_by = ARRAY['create_time'],
  extra_properties = MAP(ARRAY['write.metadata.delete-after-commit.enabled'], ARRAY['true'])
);
